#!/usr/bin/env python3
"""Generate agents/INDEX.md from agent.md frontmatter, with roster lint.

Run from the repo root: python3 scripts/build_index.py
Fails (exit 1) on lint violations so CI can gate on it later.
"""
import glob
import re
import sys

ROOT = "agents"
OUT = f"{ROOT}/INDEX.md"
# ponytail: naive frontmatter split, swap for a YAML parser if fields grow
FM = re.compile(r"^---\n(.*?)\n---", re.S)
MUTATION_TOOLS = {"Edit", "Bash", "NotebookEdit"}  # forbidden for opus, no exceptions
# Write is also forbidden for opus, except roles listed here with a reason.
OPUS_WRITE_EXCEPTIONS = {
    "agents/pm/project-manager/agent.md":
        "spec-driven PM: Write is docs/-scoped (specs, backlog, PRD drafts), never code",
}


def parse(path):
    text = open(path).read()
    m = FM.match(text)
    fm = {}
    if m:
        for line in m.group(1).split("\n"):
            if ":" in line:
                k, v = line.split(":", 1)
                fm[k.strip()] = v.strip()
    return fm


def main():
    problems = []
    teams = {}
    for path in sorted(glob.glob(f"{ROOT}/*/*/agent.md")):
        _, team, role, _ = path.split("/")
        if team == "TEMPLATE":
            continue
        fm = parse(path)
        for field in ("name", "description", "tools", "model"):
            if not fm.get(field):
                problems.append(f"{path}: missing frontmatter field '{field}'")
        spec = path.replace("agent.md", "SPEC.md")
        if not glob.glob(spec):
            problems.append(f"{path}: missing SPEC.md sibling")
        tools = {t.strip() for t in fm.get("tools", "").split(",")}
        if fm.get("model") == "opus":
            bad = tools & MUTATION_TOOLS
            if "Write" in tools and path not in OPUS_WRITE_EXCEPTIONS:
                bad = bad | {"Write"}
            if bad:
                problems.append(
                    f"{path}: opus paired with write tools {sorted(bad)}"
                    " — opus buys reasoning depth, not blast radius"
                )
        one_liner = re.split(r"(?<=[.!?]) ", fm.get("description", ""))[0]
        teams.setdefault(team, []).append(
            (role, fm.get("model", "?"), fm.get("tools", "?"), one_liner)
        )

    total = sum(len(v) for v in teams.values())
    models = {}
    for rows in teams.values():
        for _, m, _, _ in rows:
            models[m] = models.get(m, 0) + 1
    model_summary = ", ".join(f"{k}: {v}" for k, v in sorted(models.items()))

    lines = [
        "# Agent Index",
        "",
        "Generated by `scripts/build_index.py` — do not edit by hand.",
        "",
        f"**{total} agents** across **{len(teams)} teams**. Models — {model_summary}.",
        "",
    ]
    for team in sorted(teams):
        lines.append(f"## {team} ({len(teams[team])})")
        lines.append("")
        lines.append("| Role | Model | Tools | What it does |")
        lines.append("|---|---|---|---|")
        for role, model, tools, desc in teams[team]:
            lines.append(f"| [{role}]({team}/{role}/) | {model} | {tools} | {desc} |")
        lines.append("")

    open(OUT, "w").write("\n".join(lines))
    print(f"wrote {OUT}: {total} agents, {len(teams)} teams ({model_summary})")

    if problems:
        print(f"\n{len(problems)} lint problem(s):", file=sys.stderr)
        for p in problems:
            print(f"  {p}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
