#!/usr/bin/env python3
"""Stamp a new Architecture Decision Record + rebuild the ADR index (#81).

    python3 scripts/new_adr.py "<decision title>"
    python3 scripts/new_adr.py --reindex           # rebuild the index only

Allocates the next zero-padded `NNNN`, writes
`docs/adr/NNNN-<slug>.md` from `docs/templates/adr.md` with the number,
slug-title, date, and `Status: proposed` prefilled, then regenerates
`docs/adr/README.md` as the index (number · title · status · date), newest
last. Mirrors `scripts/new_sprint_log.py`: stdlib-only, refuses to overwrite,
never fabricates content — the Context/Options/Decision sections stay as
template prose for the author to fill.

ADRs are immutable once accepted: a reversal is a NEW ADR that supersedes the
old one (set the old one's Status to `superseded by ADR-MMMM`), never an edit
in place. The index is generated, so it's cheap to keep current — run
`--reindex` after hand-editing a Status line.
"""
import argparse
import datetime
import glob
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _cli  # noqa: E402

TEMPLATE = "docs/templates/adr.md"
ADR_DIR = "docs/adr"
NNNN_RE = re.compile(r"(\d{4})-.+\.md$")
STATUS_RE = re.compile(r"^\*\*Status\*\*:\s*(.+)$", re.M)
TITLE_RE = re.compile(r"^#\s+ADR-\d+:\s*(.+)$", re.M)
DATE_RE = re.compile(r"^\*\*Date\*\*:\s*(\S+)", re.M)


def slugify(title):
    s = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    return s or "decision"


def next_number(adr_dir):
    highest = 0
    for path in glob.glob(os.path.join(adr_dir, "*.md")):
        m = NNNN_RE.search(os.path.basename(path))
        if m:
            highest = max(highest, int(m.group(1)))
    return highest + 1


def render(number, title, today):
    template_path = os.path.join(_cli.repo_root(), TEMPLATE)
    text = open(template_path, encoding="utf-8").read()
    text = text.replace("# ADR-NNNN: <short decision title>",
                        f"# ADR-{number:04d}: {title}")
    text = text.replace(
        "**Status**: proposed | accepted | superseded by ADR-MMMM | deprecated",
        "**Status**: proposed")
    text = text.replace("**Date**: YYYY-MM-DD", f"**Date**: {today:%Y-%m-%d}")
    return text


def build_index(adr_dir):
    """Regenerate docs/adr/README.md from the ADR files' own headers."""
    rows = []
    for path in sorted(glob.glob(os.path.join(adr_dir, "*.md"))):
        base = os.path.basename(path)
        if base == "README.md":
            continue
        m = NNNN_RE.search(base)
        if not m:
            continue
        text = open(path, encoding="utf-8").read()
        num = int(m.group(1))
        title = (TITLE_RE.search(text).group(1).strip()
                 if TITLE_RE.search(text) else base)
        status = (STATUS_RE.search(text).group(1).strip()
                  if STATUS_RE.search(text) else "?")
        date = (DATE_RE.search(text).group(1).strip()
                if DATE_RE.search(text) else "?")
        rows.append((num, title, status, date, base))

    lines = [
        "<!-- generated by scripts/new_adr.py — do not edit by hand -->",
        "# Architecture Decision Records",
        "",
        "The index of decisions with long-term lock-in (`docs/templates/adr.md`).",
        "Each ADR is immutable once accepted; a reversal is a new ADR that",
        "supersedes, never an edit in place. Regenerate this index with",
        "`python3 scripts/new_adr.py --reindex`.",
        "",
        "| ADR | Decision | Status | Date |",
        "|---|---|---|---|",
    ]
    if not rows:
        lines.append("| — | _no ADRs yet_ | — | — |")
    for num, title, status, date, base in sorted(rows):
        lines.append(f"| [ADR-{num:04d}](./{base}) | {title} | {status} | {date} |")
    return "\n".join(lines) + "\n"


def main(argv):
    parser = argparse.ArgumentParser(
        prog="new_adr.py",
        description="Stamp a new ADR and rebuild the ADR index.")
    parser.add_argument("title", nargs="?", help="the decision title")
    parser.add_argument("--reindex", action="store_true",
                        help="rebuild docs/adr/README.md only, create no ADR")
    args = parser.parse_args(argv)

    root = _cli.repo_root()
    adr_dir = os.path.join(root, ADR_DIR)
    os.makedirs(adr_dir, exist_ok=True)

    if args.reindex:
        idx = os.path.join(adr_dir, "README.md")
        open(idx, "w", encoding="utf-8").write(build_index(adr_dir))
        print(f"rebuilt {ADR_DIR}/README.md")
        return 0

    if not args.title:
        print("new_adr.py: a decision title is required (or use --reindex)",
              file=sys.stderr)
        return 1

    today = datetime.date.today()
    number = next_number(adr_dir)
    slug = slugify(args.title)
    out_name = f"{number:04d}-{slug}.md"
    out_path = os.path.join(adr_dir, out_name)
    if os.path.exists(out_path):
        print(f"new_adr.py: refusing to overwrite {ADR_DIR}/{out_name}",
              file=sys.stderr)
        return 1

    open(out_path, "w", encoding="utf-8").write(render(number, args.title, today))
    idx = os.path.join(adr_dir, "README.md")
    open(idx, "w", encoding="utf-8").write(build_index(adr_dir))
    print(f"wrote {ADR_DIR}/{out_name} and rebuilt {ADR_DIR}/README.md")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
